---
apiVersion: v1
kind: Service
metadata:
  name: amdocstest
  labels:
    app: amdocstest
spec:
  type: NodePort
  selector:
    app: amdocstest
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: amdocstest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amdocstest
    spec:
      containers:
      - name: amdocstest
        image: rbgurav/amdocstest:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1