---
- name: install docker
  command: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- name: add deb repo
  command: sudo touch /etc/apt/sources.list.d/docker.list
- lineinfile: dest="/etc/apt/sources.list.d/docker.list" line="{{item}}"
  with_items:
    - "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
- name: apt update
  apt: update_cache=yes
- apt: name=docker-engine state=present
- name: add user mod
  command: sudo usermod -aG docker {{remote_user}}
- name: add user mod
  command: sudo usermod -aG docker {{action_user}}
- name: restart docker
  command: sudo systemctl restart docker